Module8 task1
htmlacademy-adaptive/1916729-cat-energy-26 pull request #9
Opened 2022-09-15 17:12 UTC by maruh605

2022-09-15 17:18 UTC, maruh605 commented
Привет пожалуйста помоги только более конкретно, время очень сильно поджимает. Я сравнил версии и у меня после сборки поплыли <br> в блоке Похудение и Набор массы на главной (слова слиплись), в последней опубликованной версии все шикарно. плюс коты поплыли с отображением после отпимизации, как это исправить. Ты мне накидывал по котам что их нужно исправить (я пока не трогал ошибки что ты скидывал) 5 дней на автоматизацию ушло с тренажерами. я за завтра постараюсь исправить ошибки что ты в телеграме скидывал. только умоляю, я не так часто тебя достаю, если будет возможность запиши мелкое видео. без сна уже подкидывает.

2022-09-16 09:26 UTC, Zakamsky requested changes

2022-09-16 09:26 UTC, Zakamsky commented on .gitignore
>  source/css/*.map
Эту папку можно просто удалить, зачем она нужна?

2022-09-16 09:26 UTC, Zakamsky commented on build/catalog.html
> +<!DOCTYPE html><html class="page" lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Кэт Энерджи: Функциональное питание для котов</title>
Вот ты вроде папку добавил в игнор, а файлы в репо все равно попали.

удалить можно вот так:
`git rm --cache имя_файла(ов)/папки(ок)`

только следи за корректностью путей/имен

2022-09-17 11:57 UTC, merged